displayName=10/10 Vision
author=Endrit
description=(Formerly Visibility Enhancer) Teammate opacity, ground-view filters, and outlines for raids.
tags=10/10 Vision,vision,visibility,visibility enhancer,opacity,entity,hider,entity hider,raids,raid,raids visibility enhancer,raids entity hider,toa,cox,tob,tombs of amascut,theatre of blood,chambers of xeric,boss visibility
plugins=com.visibilityenhancer.VisibilityEnhancer