displayName=Visibility Enhancer
author=Endrit
description=Visibility Enhancer is a RuneLite plugin built for raid teams that want better visibility. It is the first plugin that works with opacity to provide a better experience inside team raids and other group PvM content.
tags=visibility,visibility enhancer,opacity,entity,hider,entity hider,raids,raid,raids visibility enhancer, raids entity hider,toa,cox,tob,tombs of amascut, theatre of blood, chambers of xeric,boss visibility
plugins=com.visibilityenhancer.VisibilityEnhancer